#4 'Aims style broken' issue resolved.
SmruthyJoseph/soraytec pull request #15
Opened 2021-01-20 10:33 UTC by SmruthyJoseph

#4 **'Aims style broken'** issue resolved.

2021-01-21 04:32 UTC, SmruthyJoseph commented
#7 'Aims style broken' issue resolved.

2021-01-21 10:08 UTC, AbhijithHaridas requested changes

2021-01-21 10:08 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/front-page.php
> -
@SmruthyJoseph what is this for?

2021-01-21 10:19 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/front-page.php
> -
Sorry, That's not needed. I used the title for giving the aim style before but i changed so now it is not needed.

2021-01-21 10:21 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/front-page.php
> -
It's Okay, please remove it

2021-01-21 10:22 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/front-page.php
> -
Ok

2021-01-21 11:23 UTC, SmruthyJoseph commented
#7 Aims style issue corrected.

2021-01-21 12:08 UTC, AbhijithHaridas reviewed
@SmruthyJoseph is this working for you?

2021-01-21 12:12 UTC, SmruthyJoseph commented
Yes, It works

2021-01-21 12:15 UTC, AbhijithHaridas requested changes

2021-01-21 12:15 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/front-page.php
> +                     <?php endif; ?>
@SmruthyJoseph this is bad, find another solution

2021-01-21 12:18 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/front-page.php
> +                     <?php endif; ?>
Ok

2021-01-22 04:31 UTC, SmruthyJoseph commented
#7 Aims style issues corrected.

2021-01-22 08:07 UTC, AbhijithHaridas requested changes
Update the Aims listing to be more efficient

2021-01-23 08:48 UTC, AbhijithHaridas approved these changes

2021-01-23 08:48 UTC, merged