#5 'Homepage custom fields'
SmruthyJoseph/soraytec pull request #16
Opened 2021-01-20 11:15 UTC by SmruthyJoseph

#8 **Homepage custom fields** issue resolved.

2021-01-21 10:19 UTC, AbhijithHaridas requested changes

2021-01-21 10:28 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/functions.php
> -function footer() {
I customized footer using acf first so the function is for that and  after i changed to customizer , so i deleted the function.

2021-01-21 10:39 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/functions.php
> -function footer() {
Not in the scope of this issue

2021-01-21 10:44 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/functions.php
> -function footer() {
Ok i will reset it.

2021-01-22 06:48 UTC, SmruthyJoseph commented
#8 **Home page custom fields** issue corrected.

2021-01-22 07:27 UTC, merged