#8 issue 'Error if custom field is missing' is resolved.
SmruthyJoseph/soraytec pull request #18
Opened 2021-01-21 06:22 UTC by SmruthyJoseph

#11 **Error if custom field is missing** issue is resolved.

2021-01-21 10:17 UTC, AbhijithHaridas requested changes
@SmruthyJoseph Cleanup the **PR** changes so that it only has the changes to resolve this issue

2021-01-21 10:17 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/front-page.php
> +                <?php endif; ?>
Chance of error.
Minimize the number of **if**

2021-01-21 10:17 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/front-page.php
> +
Chance of error.
Minimize the number of **if**

2021-01-21 10:31 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/front-page.php
> +                <?php endif; ?>
ok

2021-01-21 10:31 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/front-page.php
> +
ok

2021-01-22 05:31 UTC, SmruthyJoseph commented
#11 **Error if custom field is missing** issue corrected.

2021-01-22 07:58 UTC, AbhijithHaridas requested changes
Update the if scop and correct the if indentation

2021-01-23 08:46 UTC, AbhijithHaridas approved these changes

2021-01-23 08:46 UTC, merged