#9 Validated the html pages.
SmruthyJoseph/soraytec pull request #19
Opened 2021-01-21 07:46 UTC by SmruthyJoseph

#12 Validated the html pages.

2021-01-21 10:13 UTC, AbhijithHaridas requested changes
@SmruthyJoseph Cleanup the **PR** changes so that it only has the changes to resolve this issue

2021-01-21 10:31 UTC, SmruthyJoseph commented
ok

2021-01-22 06:23 UTC, SmruthyJoseph commented
#12 Validated the html pages.

2021-01-22 07:52 UTC, AbhijithHaridas approved these changes

2021-01-22 07:52 UTC, merged