7 description content overflow
SmruthyJoseph/soraytec pull request #20
Opened 2021-01-22 05:44 UTC by SmruthyJoseph

#10 **Description content overflow** issue corrected.

2021-01-22 07:37 UTC, AbhijithHaridas approved these changes

2021-01-23 08:44 UTC, AbhijithHaridas requested changes

2021-01-23 08:44 UTC, AbhijithHaridas commented on wp-content/themes/soraytec/functions.php
> +                }
Code indentation is not correct

2021-01-23 09:23 UTC, SmruthyJoseph commented on wp-content/themes/soraytec/functions.php
> +                }
ok

2021-01-23 16:19 UTC, AbhijithHaridas approved these changes

2021-01-23 16:19 UTC, merged